name: "Build"
on:
  push:
    branches:
      - master
  schedule:
    # Random time each week.
    - cron:  '12 5 * * 3'

jobs:
  build:
    uses: silvenga-docker/building/.github/workflows/publish-github.yaml@master
    secrets: inherit
